apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-dash-ingress
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
spec:
  ingressClassName: gce-internal
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-dash-service
                port:
                  number: 80